"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConfigFields = exports.LegalBasisValues = exports.ServiceRequirementsValues = exports.ThirdPartyDataValues = exports.SensitiveInformationValues = exports.PersonalInformationValues = exports.ProhibitedUsesValues = exports.TailwindConfigFields = void 0;
exports.TailwindConfigFields = {
    headingColor: "string",
    bodyColor: "string",
    linkColor: "string",
};
exports.ProhibitedUsesValues = [
    "crawling",
    "illegal",
    "harmful",
    "infringing",
    "abusive",
    "spam",
    "advertising",
    "impersonation",
    "accountTransfer",
];
exports.PersonalInformationValues = [
    "name",
    "email",
    "phone",
    "address",
    "password",
    "ipAddress",
    "deviceId",
    "creditCard",
    "locationData",
    "anonymizedUsageData",
];
exports.SensitiveInformationValues = [
    "ssn",
    "financial",
    "health",
    "biometric",
    "genetic",
    "political",
    "sexualOrientation",
    "criminalHistory",
    "religion",
];
exports.ThirdPartyDataValues = [
    "advertising",
    "analytics",
    "socialMedia",
    "purchase",
    "email",
    "support",
    "crm",
    "job",
    "address",
    "behavior",
];
exports.ServiceRequirementsValues = [
    "accounts",
    "communication",
    "orders",
];
exports.LegalBasisValues = [
    "advertising",
    "marketing",
    "analytics",
    "security",
    "fraudPrevention",
];
exports.ConfigFields = {
    cssFramework: "select:tailwind,classes",
    tailwindConfig: exports.TailwindConfigFields,
    entityName: "string",
    entityWebsite: "string",
    supportEmail: "string",
    privacyEmail: "string",
    privacyLastUpdated: "string",
    tosLastUpdated: "string",
    platforms: ["web", "mobile"],
    locations: ["us", "eu", "uk"],
    entityLocation: "string",
    underEighteen: "boolean",
    underThirteen: "boolean",
    socialSignIn: "boolean",
    purchasableGoods: "boolean",
    subscription: "boolean",
    freeTrial: "boolean",
    autoRenew: "boolean",
    refundPolicy: "select:none,full,prorata",
    userContent: "boolean",
    userContentLicense: "boolean",
    userAccounts: "boolean",
    governingLaw: "string",
    disputeResolution: "select:arbitration,litigation",
    mediation: "boolean",
    prohibitedUses: exports.ProhibitedUsesValues,
    serviceSLA: "boolean",
    serviceSLAAmount: "number",
    serviceSLATimeframe: "optional:string",
    serviceSLARefund: "boolean",
    serviceSLARefundType: "select:full,prorata",
    serviceSLACustom: "optional:string",
    liabilityLimitation: "boolean",
    liabilityLimitationType: "select:amount_paid,amount,minAmountPaidOrAmount",
    liabilityLimitationTimeframe: "optional:string",
    liabilityLimitationAmount: "number",
    personalInformation: exports.PersonalInformationValues,
    sensitiveInformation: exports.SensitiveInformationValues,
    thirdPartyData: exports.ThirdPartyDataValues,
    paymentData: "boolean",
    paymentProcessors: "string_array",
    appUsageData: "boolean",
    thirdPartyDisclosure: "boolean",
    thirdPartyDisclosureEntities: "string_array",
    thirdPartySharing: "boolean",
    thirdPartySharingEntities: "string_array",
    securityMeasures: "boolean",
    webTracking: "boolean",
    thirdPartyAnalytics: "boolean",
    serviceRequirements: exports.ServiceRequirementsValues,
    legalBasis: exports.LegalBasisValues,
    dataRetentionPeriod: "optional:string",
    usStatePrivacyLaws: "boolean",
    privacyPage: "optional:string",
    dpo: "boolean",
    dpoName: "optional:string",
    dpoEmail: "optional:string",
    dpoPhone: "optional:string",
};
