export const DefaultConfiguration = {
    cssFramework: "tailwind",
    tailwindConfig: {
        headingColor: "text-gray-800",
        bodyColor: "text-gray-600",
        linkColor: "text-blue-500",
    },
    entityName: "",
    entityWebsite: "",
    entityAddress: "",
    supportEmail: "",
    privacyEmail: "",
    privacyLastUpdated: new Date().toISOString(),
    tosLastUpdated: new Date().toISOString(),
    platforms: ["web"],
    locations: ["us", "eu", "uk"],
    entityLocation: "us",
    underEighteen: false,
    underThirteen: false,
    socialSignIn: false,
    purchasableGoods: false,
    subscription: false,
    freeTrial: false,
    autoRenew: false,
    refundPolicy: "none",
    userContent: false,
    userContentLicense: false,
    userAccounts: false,
    governingLaw: "California",
    disputeResolution: "litigation",
    mediation: false,
    prohibitedUses: [],
    serviceSLA: false,
    serviceSLAAmount: 0,
    serviceSLATimeframe: undefined,
    serviceSLARefund: false,
    serviceSLARefundType: "full",
    serviceSLACustom: undefined,
    liabilityLimitation: false,
    liabilityLimitationType: "amount",
    liabilityLimitationTimeframe: undefined,
    liabilityLimitationAmount: 0,
    personalInformation: [],
    sensitiveInformation: [],
    thirdPartyData: [],
    paymentData: false,
    paymentProcessors: [],
    appUsageData: false,
    thirdPartyDisclosure: false,
    thirdPartyDisclosureEntities: [],
    thirdPartySharing: false,
    thirdPartySharingEntities: [],
    securityMeasures: false,
    webTracking: false,
    thirdPartyAnalytics: false,
    serviceRequirements: [],
    legalBasis: [],
    dataRetentionPeriod: undefined,
    usStatePrivacyLaws: false,
    privacyPage: undefined,
    dpo: false,
    dpoName: undefined,
    dpoEmail: undefined,
    dpoPhone: undefined,
};
